apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotnet2.1-dep
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dotnet2.1-app
    spec:
      containers:
      - name: dotnet2.1
        image: adityaregistry.azurecr.io/dotnet2.1-app:34
        ports:
        - name: dotnet2.1port 
          containerPort: 5000
apiVersion: v1
kind: Service
metadata:
  name: dotnet2.1-svc
spec:
  ports:
  - port: 8888
    nodePort: 31010
    targetPort: dotnet2.1port
    protocol: TCP
  selector:
    app: dotnet2.1-app
  type: LoadBalancer
