apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotnet21-dep
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dotnet21-app
    spec:
      containers:
      - name: dotnet21
        image: adityaregistry.azurecr.io/dotnet2.1:#{Build.BuildId}#
        ports:
        - name: dotnet21port 
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet21-svc
spec:
  ports:
  - port: 8888
    nodePort: 31111
    targetPort: dotnet21port
    protocol: TCP
  selector:
    app: dotnet21-app
  type: LoadBalancer
